#!/bin/sh

echo "Running detekt"

FILES=${git diff --cached --name-only --diff-filter=ACM | grep '/.kt$' | tr '/n' ' '}

if [ -n "$FILES" ]; then
    ./gradlew detekt --files "$FILES"
    DETEKT_STATUS=$?

    if [ "$DETEKT_STATUS" -eq 0 ]; then
        echo "Detekt Passed"
    else
        echo "Detekt Failed"
        exit 1
    fi
else
    echo "change not found"
fi
exit 0

#if [ "$status" = 0 ] ; then
#    echo "*************************************************"
#    echo "            Detekt Failed            "
#    echo "*************************************************"
#    exit 0
#else
#    echo 1>&2 "*************************************************"
#    echo "            Detekt Failed            "
#    echo "*************************************************"
#    exit 1
#fi